- pragma:
    implied-branches:
      - release-3.9-contrail
      - R5.0

- project:
    name: Juniper/openshift-ansible
    templates:
      - openshift-systests
    check:
      jobs:
        - contrail-sanity-rhel7-openshift-3.9:
            dependencies:
              - contrail-build-containers-rhel7-queens
              - contrail-build-test-containers

