- project:
    name: Juniper/openshift-ansible
    experimental:
      jobs:
        - contrail-vnc-build-package-rhel7-queens
        - contrail-build-containers-rhel7-queens:
            dependencies:
              - contrail-vnc-build-package-rhel7-queens
        - contrail-build-test-containers:
            dependencies:
              - contrail-vnc-build-package-rhel7-queens
        - contrail-deploy-rhel7-openshift-3.9:
            dependencies:
              - contrail-build-containers-rhel7-queens
              - contrail-build-test-containers
        - contrail-sanity-rhel7-openshift-3.9:
            voting: false
            dependencies:
              - contrail-build-containers-rhel7-queens
              - contrail-build-test-containers
