---
- name: Contrail wait for all pods
  hosts: oo_first_master
  command: /tmp/wait_for_pod.sh
  register: contrail_pod_status
  failed_when: "'ERROR' in contrail_pod_status.stdout"

- name: Contrail Restarting dnsmasq service
  hosts: "{{ openshift_node_scale_up_group | default('oo_nodes_to_config') }}"
  tasks:
    - name: Restart dnsmasq
      service:
        name: "dnsmasq"
        state: restarted
        enabled: yes
      when:
        - openshift_use_contrail | default(false) | bool
        - not nested_mode_contrail | default(false) | bool

- name: Opening port 53
  hosts: "{{ openshift_node_scale_up_group | default('oo_nodes_to_config') }}"
  tasks:
    - name: open udp port 53
      command: iptables -I INPUT 4 -j ACCEPT -p udp --dport 53
      when:
        - openshift_use_contrail | default(false) | bool
        - not os_firewall_use_firewalld | default(False) | bool

