---
- name: Set bind mounts for containerized install
  include_tasks: bind_mounts.yaml
  when: openshift_is_containerized | bool

- name: Set ntp on nodes
  include_tasks: ntp.yml

- name: Configure contrail controller
  include_tasks: controller_config.yaml

- name: Configure all openshift nodes
  include_tasks: node_config.yaml
