---
- name: Get contrail nodes and ips
  include_role:
    name: contrail_common

- name: Generate cert for contrail nodes
  include_tasks: etcd_certs.yaml
  when: inventory_hostname in contrail_masters

- name: Copy the cert to master folder
  include_tasks: certs_copy.yaml
  when: inventory_hostname in contrail_masters

- name: Set ntp on nodes
  include_tasks: ntp.yml

- name: Configure all openshift nodes
  include_tasks: node_config.yaml

- name: Set bind mounts for containerized install
  include_tasks: bind_mounts.yaml
  when: openshift_is_containerized | bool
