---
- name: Set ntp on nodes
  include_tasks: ntp.yml

- name: Configure contrail controller
  include_tasks: controller_config.yaml

- name: Configure all openshift nodes
  include_tasks: node_config.yaml

- name: Remove cni requirements in Master to make Master ready
  replace:
    path: /etc/origin/node/node-config.yaml
    regexp: 'networkPluginName(.*)?$'
    replace: '#networkPluginName\1'
  when: "{{ ansible_default_ipv4['address'] in contrail_masters }}"

- name: Restart atomic-openshift-node process
  systemd:
    name: atomic-openshift-node
    state: restarted
  when: "{{ ansible_default_ipv4['address'] in contrail_masters }}"

# Note: we need to move below tasks to master later, we are calling 
# here because of openshift-ansible design constraint
- name: Configure the openshift master
  hosts: groups.masters.0
  include_role:
      name: contrail_master
      tasks_from: os_contrail_master.yaml
  when: "{{ ansible_default_ipv4['address'] in groups.masters.0 }}"  

- name: Web Console install
  hosts: groups.masters.0
  include_role:
      name: contrail_master
      tasks_from: web_console_main.yaml
  when: "{{ ansible_default_ipv4['address'] in groups.masters.0 }}"
  run_once: True
