---
- name: Set ntp on nodes
  include_tasks: ntp.yml

- name: Configure contrail controller
  include_tasks: controller_config.yaml

- name: Configure all openshift nodes
  include_tasks: node_config.yaml

- name: Configure the openshift master
  include_role:
      name: contrail_master
      tasks_from: os_contrail_master.yaml
  delegate_to: "{{ groups.masters.0 }}"
