- project:
    name: Juniper/openshift-ansible
    experimental:
      jobs:
        - contrail-vnc-build-package-centos74
        - contrail-vnc-build-containers-centos7-ocata:
            dependencies:
              - contrail-vnc-build-package-centos74
        - contrail-vnc-build-test-containers:
            dependencies:
              - contrail-vnc-build-package-centos74
        - contrail-sanity-centos7-openshift-3.7:
            voting: false
            dependencies:
              - contrail-vnc-build-containers-centos7-ocata
              - contrail-vnc-build-test-containers
